import React, { Component } from 'react';

// This class is used purely for rendering the map array generated by logic.generateLevel
class Footer extends React.Component {
  render() {
    const footerContainerStyles = {
      marginTop: "3rem"
    };

    const footerIconStyles = {
      margin: "0.2rem",
      fontSize: "1.6em",
      color: "#555"
    };

    return(
      <div style={footerContainerStyles}>
        <p>
          <a href="#"><i className="fa fa-twitter" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-facebook-official" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-google-plus-official" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-linkedin" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-github" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-codepen" style={footerIconStyles}></i></a>
          <a href="#"><i className="fa fa-envelope-o" style={footerIconStyles}></i></a>
        </p>
        <p>This game was created in fulfilment of the Build a Roguelike Dungeon Crawler Game project of the Free Code Camp curriculum</p>
      </div>
    );
  }
}

export default Footer;
