import React, { Component } from 'react';
import './Map.css';

// This class is used purely for rendering the map array generated by logic.generateLevel
class Map extends React.Component {
  render() {
    let renderedMap = this.props.map.map((row, rowIndex) => {
      return (
        <div className={"Map-row"} data-row={rowIndex}>
          {
            row.map((tile, tileIndex) => {
              return <div className="Map-tile" data-x={tile.x} data-y={tile.y} data-terrain={tile.terrain} data-roomId={tile.roomId} data-player={tile.player} data-objectId={tile.object.id} data-dialogueId={tile.object.dialogueId}></div>
            })
          }
        </div>
      );
    });

    return(
      <div className="Map" style={this.props.style}>{renderedMap}</div>
    );
  };
}

export default Map;
